### ISSUE TITLE
pinch里设置originX基准点后，基准点会先跳到画布正中点位置再进行缩放

### ISSUE THREAD

**Issue by junxiachen2** [AlloyTeam/AlloyFinger#106]
pinch里设置originX基准点后，基准点会先跳到画布正中点位置再进行缩放，请问下有没啥办法，直接就原来位置进行缩放，而不先将基准点跳到画布中间。谢谢~

**Comment by dntzhang** [comment]
参照alloycrop的优化 https://github.com/AlloyTeam/AlloyCrop#pinch-%E7%BC%A9%E6%94%BE%E4%BC%98%E5%8C%96

**Comment by junxiachen2** [comment]
太好了，谢谢
