### ISSUE TITLE
Does it make sense to spawn > 10 empty functions?

### ISSUE THREAD

**Issue by kurtextrem** [AlloyTeam/AlloyFinger#18]
see title.

Maybe a function to call functions would solve the issue:
```
call: function (method) {
return typeof this[method] === 'function' ? this[method]() : false;
}
```

**Comment by kmdjs** [comment]
An even more concise way !  thanks.
But every time the execution should be check -> typeof this[method] === 'function'~~
I'm a perfectionist. I can not accept the checking.

**Comment by kurtextrem** [comment]
Ah yes, true.
Then another idea:
```
var noop = function() {}
this.rotate = options.rotate || noop
this.touchStart = options.rotate || noop
```
and so on. That would only spawn one empty function and doesn't require checking :)

**Comment by kmdjs** [comment]
good idea. done. https://github.com/AlloyTeam/AlloyFinger/commit/93e6ee60799d4d787d5fac1c725b737f4c68d99e

**Comment by kurtextrem** [comment]
Perfect! :)
