### ISSUE TITLE
什么时候支持 vue2.1.3 哦。。。

### ISSUE THREAD

**Issue by ringcrl** [AlloyTeam/AlloyFinger#22]
很喜欢 AlloyFinger~什么时候支持Vue 2.1.3 呢？

**Comment by kmdjs** [comment]
快了！  @JuneAndGreen 正在搞~~

**Comment by kmdjs** [comment]
@ringcrl 
 @JuneAndGreen 的vue1刚出炉 https://github.com/AlloyTeam/AlloyFinger/tree/master/vue1

**Comment by ringcrl** [comment]
@kmdjs 好激动！！！在搞了！！

可是已经回不去vue1的时代了😭😭😭。。

**Comment by ringcrl** [comment]
@kmdjs 虽然所有项目都是用vue2来写，可是对vue还不是很精通，不知道怎么改代码才能兼容2。。

**Comment by kmdjs** [comment]
@ringcrl 
vue2也支持了。试试 https://github.com/AlloyTeam/AlloyFinger/tree/master/vue 
任何问题欢迎骚扰 @JuneAndGreen

**Comment by ringcrl** [comment]
@kmdjs 666得飞起，我这就在项目里面试试~~

**Comment by ringcrl** [comment]
@JuneAndGreen 我来骚扰了。。。

为啥 npm 的栗子和 example 的栗子不一样哟
https://www.npmjs.com/package/vue-finger

我就是想实现一下
http://alloyteam.github.io/AlloyFinger/

里面的 pinch 栗子。。。现在突然不知道怎么下手诶。。

**Comment by ringcrl** [comment]
@JuneAndGreen @kmdjs 
```
<template>
  <div class="page-index">
    <div class="imgBox">
      <img ref="imgPinch" v-finger:pinch="onPinch" id="pinchImg" src="../assets/img/test.png">
    </div>
  </div>
</template>
<style lang='scss' scoped>
.page-index {
  margin: 0;
  padding: 0;
  border: 0;
  background-color: #ccc;
  text-align: center;
  font: 14px / 1.5 "Helvetica Neue", Helvetica, Arial, "Microsoft Yahei", "Hiragino Sans GB", "Heiti SC", "WenQuanYi Micro Hei", sans-serif;
  .imgBox {
    margin-bottom: 10px;
    border-bottom: 1px solid #333333;
    img {
      width: 160px;
    }
  }
}
</style>
<script>
export default {
  data: function() {
    return {
      initScale: 1
    }
  },
  methods: {
    onPinch: function(evt) {
      this.$refs.imgPinch.scaleX = this.$refs.imgPinch.scaleY = this.initScale * evt.scale;
    }
  }
}
</script>
```

这是我的模仿代码。。

**Comment by ringcrl** [comment]
为了模仿得更像一点，把 `Transform` 也引进来了，但是好像npmjs上面那个不是你们这个？

```
<template>
  <div class="page-index">
    <div class="imgBox">
      <img ref="imgPinch" v-finger:pinch="onPinch" v-on:multipoint-start="onMultipointStart" src="../assets/img/test.png">
    </div>
  </div>
</template>
<style lang='scss' scoped>
.page-index {
  margin: 0;
  padding: 0;
  border: 0;
  background-color: #ccc;
  text-align: center;
  font: 14px / 1.5 "Helvetica Neue", Helvetica, Arial, "Microsoft Yahei", "Hiragino Sans GB", "Heiti SC", "WenQuanYi Micro Hei", sans-serif;
  .imgBox {
    margin-bottom: 10px;
    border-bottom: 1px solid #333333;
    img {
      width: 160px;
    }
  }
}
</style>
<script>
export default {
  data: function() {
    return {
      initScale: 1
    }
  },
  methods: {
    onMultipointStart: function() {
      this.initScale = this.$refs.imgPinch.scaleX;
    },
    onPinch: function(evt) {
      this.$refs.imgPinch.scaleX = this.$refs.imgPinch.scaleY = this.initScale * evt.scale;
    }
  },
  mounted: function() {
    Transform(this.$refs.imgPinch)
  },
}
</script>

```

手势就是么有反应哦。。。但其实手势是生效的了。。。@JuneAndGreen @kmdjs

不回复我今天下不了班了😭

**Comment by JuneAndGreen** [comment]
@ringcrl 你发的那个npm上的那个应该是其他同学写的。

我补的这个vue版本例子我放到github上根目录下的vue目录里了，你看看？

**Comment by ringcrl** [comment]
@JuneAndGreen 我看到了哈，那我怎么用 npm 引入这个版本哦。。

关键不是引入。。是那个 pinch 的效果。。它不生效。。。完全根据 AlloyFinger 里面的 DEMO 改的。。。

**Comment by JuneAndGreen** [comment]
@ringcrl npm这块得等 @kmdjs 整理一下再发哈~

**Comment by leenty** [comment]
@ringcrl 你是怎么引入的？我现在是vue1.0,在Vue.use(AlloyFinger)的时候是报错的，如果直接引入的话监听是有，但不会触发

**Comment by JuneAndGreen** [comment]
@ringcrl @leenty  因为之前写的vue版本体验不好，现在改成插件和指令形式了哈，像`Vue.use(AlloyFingerVue);`引入使用插件。

具体使用方式可以看看[readme](https://github.com/AlloyTeam/AlloyFinger/blob/master/README.md#vue1--vue2-version)或[demo](https://github.com/AlloyTeam/AlloyFinger/tree/master/vue/example)。

**Comment by leenty** [comment]
@JuneAndGreen 多谢啦，我把`https://github.com/AlloyTeam/AlloyFinger/blob/master/vue/alloy_finger.vue.js`放在我的项目里，已经成功的引入了(^o^)
希望可以建一个库，可以让vue也方便的使用你们的AlloyFinger

**Comment by mov1er** [comment]
@JuneAndGreen 
请问alloy_finger不能传参吗？vue2用的

**Comment by yongerhappy** [comment]
我的pinch效果也出不来 不知道为什么  网上也没看到谁成功过

**Comment by wsygdiv** [comment]
确实，有手势的方法，但是真正缩放就是就没有介绍，能打印evt.zoom，但是怎么实现缩放的
