### ISSUE TITLE
swipe 事件源码疑问

### ISSUE THREAD

**Issue by syaka-yin** [AlloyTeam/AlloyFinger#39]
在查看 alloy_finger 源码的时候，对 swipe 事件的判断有些疑问。截图如下：
195 行
![image](https://cloud.githubusercontent.com/assets/4370991/23091227/00ab8518-f5ec-11e6-878a-27b4c61a4b6a.png)

判断是否 swipe 事件， Y 轴方向用的是 `Math.abs(this.preV.y - this.y2) > 30`
其中 `this.y2` 是在 `move` 函数中设置的；
而只有 `touches.length > 1` 时，才会在 `start` 和 `move` 函数中设置 `this.preV.y`，否则 `this.preV` 的值是 `{ x: null, y: null }`

是不是意味着，如果只是一根手指滑动，依次触发 touchstart touchmove touchend
那么 `end` 函数判断 swipe 的这句代码，由于 `this.preV.y` 值为 null 导致 `Math.abs(this.preV.y - this.y2) > 30` 报错呢？是不是应该改成 `Math.abs(this.y1 - this.y2) > 30` 呢？

**Comment by dntzhang** [comment]
多谢，已fix~~ 感谢你的细心review。多谢~~
