### ISSUE TITLE
vue-cli引入AlloyFinger绑定事件方法中console.log(this)报错

### ISSUE THREAD

**Issue by 262060984** [AlloyTeam/AlloyFinger#53]
npm安装AlloyFinger后
```
import AlloyFinger from 'alloyfinger';
import AlloyFingerVue from './libs/alloy_finger.vue';

Vue.use(AlloyFingerVue, { AlloyFinger });
```
绑定事件
```
    <div style="width: 100%; height: 40px; text-align: center;" v-finger:tap="tap">
      <span>↑</span>
    </div>
```
tap方法
```
    tap() {
      console.log(this);
    },
```
结果报错
[Vue warn]: Property or method "splice" is not defined on the instance but referenced during render. Make sure to declare reactive data properties in the data option.

**Comment by echolevan** [comment]
import AlloyFinger from 'alloyfinger/alloy_finger';
import AlloyFingerVue from 'alloyfinger/vue/alloy_finger.vue';

Vue.use(AlloyFingerVue, { AlloyFinger });
