### ISSUE TITLE
pressMove事件有问题

### ISSUE THREAD

**Issue by TNT-Likely** [AlloyTeam/AlloyFinger#54]
元素拖不动不知道怎么回事，pressmove事件有响应，但是对应的位移只有0,1,2这样子

**Comment by dntzhang** [comment]
本来就是-1 -2 0 1 2 啊 。就是两次move之间的间距啊~~

**Comment by TNT-Likely** [comment]
@dntzhang  后来也发现了，这回速度有点慢啊，这个issue我关掉了。
