### ISSUE TITLE
这个是如何避免点透问题的呢？

### ISSUE THREAD

**Issue by zhouzhongyuan** [AlloyTeam/AlloyFinger#7]

**Comment by kmdjs** [comment]
这个不会点透。你可以试试。 @zhouzhongyuan

**Comment by zhouzhongyuan** [comment]
这个我刚才试过了，确实不会有点透问题！

- 请问哪些代码或者什么原理避免点透的呢？
- 我看你是使用了preventDefault(多点触控)，
- 但是tap(单点触控)是如何避免点透的呢？

**Comment by kmdjs** [comment]
@zhouzhongyuan  点透主要是触发底部click或或者底部的input唤起键盘的时候，上层已经消失。
首先，AlloyFinger的事件是tap是绑在元素自身上而非冒泡到body
再次，setTimeout 0让事件触发同步转异步，即touchend的时候不是立即让上层消失。

**Comment by zhouzhongyuan** [comment]
非常感谢
