### ISSUE TITLE
vue通过vue-router跳转后，tap，long-tap都没反应

### ISSUE THREAD

**Issue by EnterWL** [AlloyTeam/AlloyFinger#72]
在main.js里通过这样引入的
import AlloyFinger from 'alloyfinger/alloy_finger'
import AlloyFingerVue from 'alloyfinger/vue/alloy_finger.vue'

Vue.use(AlloyFingerVue,{
  AlloyFinger
});

通过vue-router跳转之后，绑定的tap，tap-long事件就都没反应了

**Comment by keenjaan** [comment]
@EnterWL 你的bug可能与我遇到的是一样的，请移步https://github.com/AlloyTeam/AlloyFinger/issues/77
