### ISSUE TITLE
vue2.0中使用pinch打印scale显示未定义

### ISSUE THREAD

**Issue by wsygdiv** [AlloyTeam/AlloyFinger#81]
pinch: function(evt) {
				alert(evt.scale);
				console.log('onPinch');
	},

**Comment by mikelrmb** [comment]
用zoom

**Comment by wsygdiv** [comment]
zoom不是页面缩放吗，我想要图片的缩放

**Comment by wsygdiv** [comment]
而且引入transform.js后怎么用transform()的方法，在method{}方法里写吗？还是在哪里

**Comment by wsygdiv** [comment]
用zoom怎么算手指缩放比例啊
