### ISSUE TITLE
在pinch的手势的响应问题。

### ISSUE THREAD

**Issue by mikelrmb** [AlloyTeam/AlloyFinger#82]
感谢团队的分享，AlloyFinger非常好用，但是我发现一个关于pinch的问题。
我在vue中通过v-finger:pinch添加了手势，但是发现pinch的手势在第一次也就是两根手指按下的时候就已经触发了，这导致了当图片比较大的时候，缩小变得困难（两根手指刚触摸到手机时已经触发了一次pinch的事件，导致图片又变大），理想的情况应该是手指移动的时候才会触发。

希望给予解决的思路，谢谢。

**Comment by dntzhang** [comment]
https://github.com/AlloyTeam/AlloyFinger/blob/master/example/simple/index.html#L47-L49
参照这个啊

**Comment by wsygdiv** [comment]
我是用脚手架搭的vue2.0项目，怎么使用tranform()啊在哪里用

**Comment by wsygdiv** [comment]
export default {
		name: "demoDetailsBigImage",
		props: ['serviceUrl'],
		data: () => ({
			msg: [],
			initScale: 1,
			flag: 0,
			bigImage: {
				notNextTick: true,

				observer: true, //修改swiper自己或子元素时，自动初始化swiper
				observeParents: false, //修改swiper的父元素时，自动初始化swiper
				onSlideChangeEnd: function(swiper) {
					swiper.update();
				},

				// zoom : true,
				// zoomMax: 4,

				// direction: 'vertical',
				// autoHeight: true,
				// slidesPerView: 'auto',
			},
		}),
		computed: {
			demoDetailsFn() {
				return this.$refs.bigImage.swiper
			},
		},
		methods: {
			methodName() {

			},
			tap: function(evt) {
				//	            let that = this;
				//		    console.log(that.$refs.myBox);
				//		    let imgL = that.$refs.myBox;
				//		    imgL.height = imgL.height*2;
				//		    console.log(imgL.length)
				//		    for (var i = 0;i<imgL.length ; i++) {
				//               imgL[i].height = imgL[i].height*2;
				//               imgL[i].width = "100%";
				//               console.log(imgL[i].width)
				//		    	 console.log(imgL[i].height)
				//		    }			
				console.log('onTap');

			},
			multipointStart: function() {
				console.log('onMultipointStart');
			},
			longTap: function() {
				console.log('onLongTap');
			},
			swipe: function(evt) {
				console.log("swipe" + evt.direction);
				console.log('onSwipe');
			},
			pinch: function(evt) {
				alert(evt.zoom);
				console.log('onPinch');
			},
			rotate: function(evt) {
				console.log(evt.angle);
				console.log('onRotate');
			},
			pressMove: function(num, evt) {
				console.log(evt.deltaX);
				console.log(evt.deltaY);
				console.log('onPressMove with params:' + num);
			},
			multipointEnd: function() {
				console.log('onMultipointEnd');
			},
			doubleTap: function() {
				var img = document.getElementsByClassName("img");
				//				 Transform(img);
				console.log(img.scaleX)
				if(img.scaleX === 1) {
					new To(img, "scaleX", 2, 500, ease);
					new To(img, "scaleY", 2, 500, ease);
				} else if(img.scaleX === 2) {
					new To(img, "scaleX", 1, 500, ease);
					new To(img, "scaleY", 1, 500, ease);
				}
				//				       let that = this;
				//		    console.log(that.$refs.myBox);
				//		    let imgL = that.$refs.myBox;
				//		    imgL.height = imgL.height*2;
				//				console.log('onDoubleTap');
			},
			singleTap: function() {
				//				console.log('onSingleTap');
			},

			touchStart: function() {
				//				console.log('onTouchStart');
			},
			touchMove: function() {
				//				console.log('onTouchMove');
			},
			touchEnd: function() {
				//				console.log('onTouchEnd');
			},
			touchCancel: function() {
				//				console.log('onTouchCancel');
			}
		},
		mounted() {
			//do something after mounting vue instance
			console.log(this.$route.params.demoId);

			//加载默认数据 Start
			this.$http({
				url: this.serviceUrl + "app/works_message.htm",
				// url: "",
				method: "POST",
				params: {
					worksId: this.$route.params.demoId,
					// worksId: 85,
				},
				headers: {
					"Content-Type": "x-www-from-urlencoded"
				}
			}).then((res) => {
				this.msg = res.data;
				// console.log(JSON.stringify(res.data));
			}, (res) => {
				console.log("error from 案例详情demoDetails.vue");
			});
			//加载默认数据 Start
		}
	}
我的tranform()要在哪里用呢

**Comment by wsygdiv** [comment]
transform()方法在哪里调用啊，不调用怎么缩放图片呢

**Comment by mikelrmb** [comment]
@dntzhang 感谢
