### ISSUE TITLE
swipe 事件 移动距离小于 30 不催发 怎么解决

### ISSUE THREAD

**Issue by joyhao** [AlloyTeam/AlloyFinger#98]
swipe 事件 移动距离小于 30 不催发 怎么解决

**Comment by dntzhang** [comment]
本来就应该大于30才触发啊

**Comment by joyhao** [comment]
@dntzhang  我有张图片如果滑动一下，但是滑动距离小于30， 这时我想让这张图片 ，回到滑动前的位置，应该在上面事件里面写

**Comment by joyhao** [comment]
我在touchend里面 打印错东西了，现在可以实现啦
